carts/urls.py
from django.urls import path

from .views import CartView

urlpatterns = [
	path('',CartView.as_view(),name='cart_view'),
]

gebeya/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from products import urls as product_url

urlpatterns = [
    path('admin/', admin.site.urls),
	path('',include('products.urls')),
	path('cart/',include('carts.urls')),
	path('login/',auth_views.LoginView.as_view(),name='login'),
]

if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import ProductListView, ProductDetailView


urlpatterns = [
	path('',ProductListView.as_view(),name='product_list'),
	path('<int:pk>/',ProductDetailView.as_view(),name='product_detail'),
	
]

carts/models.py
from decimal import Decimal
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.db.models.signals import pre_save, post_save

from products.models import Product

class CartItem(models.Model):
	cart = models.ForeignKey('Cart',on_delete=models.CASCADE)
	item = models.ForeignKey(Product,on_delete=models.CASCADE)
	quantity = models.PositiveIntegerField(default=1)
	line_item_total = models.DecimalField(max_digits=12,decimal_places=2)
	
	def __str__(self):
		return self.item.title
	def remove(self):
		return "%s?item=%s&delete=True" % (reverse('cart_view'),self.item.id)
	
def cart_item_reciver(sender,instance,*args,**kwargs):
	qty = instance.quantity
	if qty >= 1:
		price = instance.item.get_price()
		line_item_total = Decimal(qty)*Decimal(price)
		instance.line_item_total = line_item_total

pre_save.connect(cart_item_reciver,sender=CartItem)
def car_item_post_save(sender,instance,*args,**kwargs):
	instance.cart.update_total()
post_save.connect(car_item_post_save,sender=CartItem)

class Cart(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,null=True,blank=True)
	items = models.ManyToManyField(Product, through=CartItem)
	timestamp = models.DateTimeField(auto_now_add=True,auto_now=False)
	updated = models.DateTimeField(auto_now_add=False,auto_now=True)
	sub_total = models.DecimalField(max_digits=12,decimal_places=2)
	
	def update_total(self):
		subtotal = 0
		items = self.cartitem_set.all()
		for item in items:
			subtotal += item.line_item_total
		self.sub_total = subtotal
		self.save()
	
	def __str__(self):
		return str(self.id)
	

products/models.py
from django.db import models
from django.utils import timezone
from django.utils.text import slugify

class ProductQueryset(models.query.QuerySet):
	def active(self):
		return self.filter(active=True)

class Product(models.Manager):
	def get_queryset(self):
		return ProductQueryset(self.model,using=self._db)
	
	def all(self,*args,**kwargs):
		return self.get_queryset().active()
	
class Product(models.Model):
	title = models.CharField(max_length=120)
	description = models.TextField(blank=True,null=True)
	pub_date = models.DateTimeField(auto_now_add=True,auto_now=False)
	inventory = models.PositiveIntegerField(default=1)
	price = models.PositiveIntegerField()
	sale_price = models.PositiveIntegerField()
	active = models.BooleanField(default=True)
	
	def __str__(self):
		return  self.title
	
	def get_price(self):
		if self.sale_price is None:
			return self.sale_price
		else:
			return self.price
	

class Specification(models.Model):
	product = models.ForeignKey(Product,on_delete=models.CASCADE)
	title = models.CharField(max_length=120)
	description = models.CharField(max_length=250)
	
	def __str__(self):
		return self.title
	


def image_upload_to(instance, filename):
	title = instance.product.title
	slug = slugify(title)
	basename, file_extension = filename.split(".")
	new_filename = "%s-%s.%s" % (slug, instance.id, file_extension)
	return "products/%s/%s" % (slug, new_filename)


class ProductImage(models.Model):
	product = models.ForeignKey(Product,on_delete=models.CASCADE)
	image = models.ImageField(upload_to=image_upload_to)
	
	def __str__(self):
		return self.product.title
	
	

carts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.views import View
from django.views.generic.detail import SingleObjectMixin

from .models import Cart, CartItem
from products.models import Product

class CartView(SingleObjectMixin,View):
	model = Cart
	
	def get_object(self,*args,**kwargs):
		cart_id = self.request.session.get("cart")
		if cart_id == None:
			cart = Cart()
			cart.save()
			cart_id = cart.id
			self.request.session["cart"] = cart_id
		cart = self.model.objects.get(id=cart_id)
		# if self.request.user.is_authenticated():
		# 	cart.user = self.request.user
		# 	cart.save()
		# cart = self.model.objects.get(id=cart_id)
		return cart
	
	
	def get(self,request,*args,**kwargs):
		cart = self.get_object()
		if request.is_ajax():
			print(request.GET.get("item"))
			return JsonResponse({"success":True})
			
		item_id = request.GET.get("item")
		qty = request.GET.get("qty",1)
		item_delete = request.GET.get("delete",False)
		if item_id:
			item = get_object_or_404(Product,id=item_id)
			try:
				if int(qty) < 1:
					item_delete = True
			except:
				raise Http404
			cart_item = CartItem.objects.get_or_create(item=item,cart=cart)[0]
			if item_delete:
				cart_item.delete()
			else:
				cart_item.quantity = int(qty)
				cart_item.save()
			
			
		return render(request,'carts/view.html',{"object":self.get_object()})
		

products/views.py
from django.shortcuts import render
from django.db.models import Q

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Product, ProductImage, Specification



class ProductListView(LoginRequiredMixin,ListView):
	model = Product
	template_name = 'products/product_list.html'
	
	def get_queryset(self,*args,**kwargs):
		qs = super(ProductListView, self).get_queryset(*args,**kwargs)
		query = self.request.GET.get("item")
		if query:
			qs = self.model.objects.filter(
				Q(title__contains=query) |
				Q(description__contains=query)
			)
		return qs
	
	
class ProductDetailView(DetailView):
	model = Product
	context_object_name = 'product'
	template_name = 'products/product_detail.html'

carts/templates/carts/view.html
{% extends 'products/base.html' %}
{% block body %}
	{% if object.cartitem_set.count > 0 %}
		<div class="container">
		<table class="table">
		{% for item in object.cartitem_set.all %}
			<tr>
				<td>{{ item.item.title }}</td>
				<td>{{ item.quantity }}</td>
				<td>{{ item.line_item_total }}</td>
				<td><a href="{{ item.remove }} " class="btn btn-link">X</a> </td>
			</tr>
		{% endfor %}
		<tr>
			<td colspan="4">Total {{ object.sub_total }}</td>
		</tr>
		</table>
		</div>
	{% endif %}
{% endblock %}

products/templates/products/base.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block titleblock %}
		{% endblock %}
	</title>
	{% load static %}
	<link href="{% static 'products/css/bootstrap.css' %}" type="text/css">
	<link href="{% static 'products/css/bootstrap.min.css' %}" type="text/css" rel="stylesheet">
	<link href="{% static 'products/css/bootstrap-grid.css' %}" type="text/css">
	<link href="{% static 'products/css/bootstrap-reboot.css' %}" type="text/css">
	<script src="{% static 'products/js/jquery.js' %}"></script>
	<script>
		$("document").ready(function () {
			{% block jquery %}
			{% endblock %}
        })
	</script>
</head>
<body>

<div class="container">

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'product_list' %}">Gebeya</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Product <span class="sr-only">(current)</span></a>
    </ul>
	  <ul class="navbar-nav ml-auto">
		  <li class="nav-item">
			  <a class="nav-link" href="{% url 'cart_view' %}"><i class="fa fa-shopping fa-navbar-cart"></i><span class="badge">0</span> </a>
		  </li>

	  </ul>

    <form class="form-inline my-2 my-lg-0" method="get" action="{% url 'product_list' %}">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="item">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
</div>
{% block body %}
{% endblock %}

		<script src="{% static 'products/js/jquery.js' %}"></script>
        <script src="{% static 'products/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'products/js/tether.min.js' %}"></script>
        <script src="{% static 'products/js/bootstrap.min.js' %}"></script>
</body>
</html>

products/templates/products/product_detail.html
{% extends 'products/base.html' %}
{% block body %}
<div class="container">

		<div class="card col-sm-8 mt-4">
		{% if product.productimage_set.count == 1 %}
	  		<img src="{{ product.productimage_set.all.first.image.url }}" class="card-img-top img-responsive" alt="...">
		{% endif %}
	  		<div class="card-body">
			<h5 class="card-title">{{ product.title }}</h5>
			<p class="card-text">{{ product.description }}</p>
				{% if product.specification_set.count > 0 %}
					<table class="table">
					{% for pro in product.specification_set.all %}
						<tr><td>{{ pro.title }}</td><td>{{ pro.description }}</td></tr>
					{% endfor %}
					</table>
				{% endif %}
			<a href="#" class="btn btn-primary align-center">Add to Cart</a>
	  	</div>
		</div>
</div>

{% endblock %}

products/templates/products/product_list.html
{% extends 'products/base.html' %}
<script>
{% block jquery %}
	$(".add-to-cart").click(function(event){
		event.preventDefault();
		var formData = $(".add-form").serialize();
		console.log(formData)
		$.ajax({
			type:"GET",
			url: "{% url 'cart_view' %}",
			data: formData,
			success:function (data) {
				console.log(data)
            },
			error:function (response,error) {
				console.log(response)
				console.log(error)
            }
		})
	})
{% endblock %}
</script>
{% block body %}
<div class="container mt-2">

<div class="row">
	{% for pro in object_list %}
		<div class="card col-sm-3 ml-4 mb-2">
		{% if pro.productimage_set.count == 1 %}
	  		<img src="{{ pro.productimage_set.all.first.image.url }}" class="card-img-top img-responsive" alt="...">
		{% endif %}
	  		<div class="card-body">
			<h5 class="card-title">{{ pro.title }}</h5>
			<p class="card-text">{{ pro.description }}</p>
			<a href="{% url 'product_detail' pro.pk %}" class="btn btn-primary">Detail</a>
				<form class="add-form" style="display: inline-block" method="get" action="{% url 'cart_view' %}">
					<input type="hidden" name="item" value="{{ pro.id }}">
					<input type="hidden" name="qty" value="1">
					<input type="submit" class="btn btn-primary align-center add-to-cart" value="Add to Cart">

				</form>
{#			<a href="{% url 'cart_view' %}?item={{ pro.pk }}&qty=1" class="btn btn-primary align-center add-cart">Add to Cart</a>#}
	  	</div>
		</div>
	{% endfor %}
	</div>
</div>
{% endblock %}s